### ISSUE TITLE
Improve the frontend of this app

### ISSUE THREAD

**Issue by shoumikdey** [shoumikdey/brute-force#19]
Create a beautiful frontend for this app using any framework. Preferably bootstrap.

**Comment by sudiptog81** [comment]
Working on this, shall interface using AJAX!

**Comment by hasan-haider** [comment]
Can I try using bootstrap? Would you elaborate what all should be present on the screen? 
Should there be any additional page/information like Readme/About?

**Comment by shoumikdey** [comment]
> Can I try using bootstrap? Would you elaborate what all should be present on the screen?
> Should there be any additional page/information like Readme/About?

Yes of course !! As of now, there aren't any specifications on what is to be there on the screen. A barebone HTML page is there, use your wit to modify it without breaking the app.

**Comment by hasan-haider** [comment]
Ok I'll add a clean and simple frontend and let you know all the modifications
